/**
 * Global exclusion list for generated metadata and disk identity files.
 *
 * These files are generated by macOS or Waypoint and have no user value in a
 * backup file set. They create false-positive duplicates, inflate diff results,
 * and cause spurious copy errors when the destination already has a different
 * version.
 *
 * Applied at every stage: scan (skip indexing), diff (filter queries),
 * and duplicate detection. Copy inherits the filter from diff.
 */

/**
 * Returns true if a filename should be excluded from indexing and all
 * downstream processing.
 *
 * Matches:
 *   - `.DS_Store`          - Finder metadata
 *   - `._*`                - resource fork / extended attribute sidecar files
 *   - `.waypoint-disk-id`  - Waypoint disk identity file
 */
export function isExcludedName(filename: string): boolean {
  return filename === ".DS_Store" ||
    filename === ".waypoint-disk-id" ||
    filename.startsWith("._");
}

/**
 * SQL WHERE clause fragment that mirrors `isExcludedName` for query-time
 * filtering. Handles files from previous scans that are already in the DB.
 *
 * Usage: `WHERE disk_id = ? AND ${EXCLUDED_NAMES_SQL}`
 */
export const EXCLUDED_NAMES_SQL = `
  name != '.DS_Store'
  AND name != '.waypoint-disk-id'
  AND name NOT LIKE '.\\_%' ESCAPE '\\'
`;
